//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetDeploy.Model
{
    using System;
    
    public partial class ProjectVersionToBundleVersion
    {
        public int Id { get; set; }
        public int ProjectVersionId { get; set; }
        public int BundleVersionId { get; set; }
        public Nullable<int> PackagerId { get; set; }
    
        public virtual BundleVersion BundleVersion { get; set; }
        public virtual ProjectVersion ProjectVersion { get; set; }
    }
}
